// // This page is a generic layout for pages generated by dynamic routes
// import Layout from '../../components/layout'
// import { connectToDatabase } from '../../util/mongodb'
// import { getAllPostIds, getPostData } from '../../lib/posts'

// const Post = ({ postData }) => {
//   console.log(postData)
//   return (
//     <Layout>
//       {postData.title}
//       <br />
//       {postData.date}
//       <br />
//       {postData.body}
//     </Layout>
//   )
// }

// export async function getServerSidePaths() {
//   const paths = await getAllPostIds()

//   return {
//     paths: JSON.parse(JSON.stringify(paths)),
//     fallback: false
//   }
// }

// export async function getServerSideProps({ params }) {
//   const postData = await getPostData(params.id)

//   return {
//     props: {
//       postData: JSON.parse(JSON.stringify(postData))
//     }
//   }
// }

// export default Post