// This page is a generic layout for pages generated by dynamic routes
import { ObjectId } from 'mongodb'
import Layout from '../../components/layout'
import { connectToDatabase } from '../../util/mongodb'
import Head from 'next/head'

export default function Post({ data }) {
  // add styling later
  if (data) {
    return (
      <Layout>
        <Head>
          <title>{data[0].title}</title>
        </Head>

        <h1>{data[0].title}</h1>
        <div>
          <p>{data[0].created}</p>
        </div>
        <br />
        <p>{data[0].body}</p>

      </Layout>
    )
  } else {
    return <div>Loading content...</div>
  }

}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true
  }
}

export async function getStaticProps({ params }) {
  const { db } = await connectToDatabase();
  const data = await db.collection("posts")
    .find({
      _id: ObjectId(params.id)
    }, {
      projection: {
        title: 1,
        created: 1,
        body: 1
      }
    }).toArray()
  return {
    props: { data: JSON.parse(JSON.stringify(data)) },
    revalidate: 1,
  }
}

//JSON.parse(JSON.stringify(data))