// This page is a generic layout for pages generated by dynamic routes
import Layout from '../../components/layout'

const Post = ({ postData }) => {
  return (
    <Layout>
      {postData.title}
      <br />
      {postData.date}
      <br />
      {postData.body}
    </Layout>
  )
}

export default Post

export async function getStaticProps() {
  
}